# Generated by Django 5.0.7 on 2024-07-26 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_amount",
            field=models.IntegerField(verbose_name="Сумма оплаты"),
        ),
    ]
