# Generated by Django 5.0.7 on 2024-07-23 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0002_lesson_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Укажите ссылку на видео",
                max_length=250,
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
