# Generated by Django 5.0.7 on 2024-07-24 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0003_alter_lesson_video_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course",
            old_name="name",
            new_name="course_name",
        ),
        migrations.RenameField(
            model_name="lesson",
            old_name="name",
            new_name="lesson_name",
        ),
    ]
